### ISSUE TITLE
How to use it?? 

### ISSUE THREAD

**Issue by raphyjb** [ItzLevvie/Agar.io-files#1]
downloaded it got 2 startdownload thingy
Could i get help on how to use it!?

**Comment by raphyjb** [comment]
Never mind google how to open a .sh file on windows.. just needed to put it in bat

**Comment by ItzLevvie** [comment]
Use the .sh on Koding

**Comment by raphyjb** [comment]
koding?? Wats that!

**Comment by ItzLevvie** [comment]
koding.com

**Comment by raphyjb** [comment]
well it doesnt work... its really wierd when downloading, it goes directly to the root folder and paste in there.. and not in folder i put it in..
Also when i put it as bat, on windows i only get files
when i put on vps i get the rest of the folders and some docs but not all.. :/ possible to get a link to download? :/

**Comment by ItzLevvie** [comment]
You can use the script on C9 then download the workspace after that you'll have to go online and find the old files (protocol 6)

**Comment by raphyjb** [comment]
so complicated for me to do this ive tryed but i dont know how ok.. :/
Maybe do a link to download? Please! (:
